#!/usr/bin/env bash
# asdf-plugin: asdf
SCRIPTPATH="$(realpath "$0")"
INSTALLPATH="${SCRIPTPATH/shims/installs}"
LATEST="$(ls "${INSTALLPATH}" | tail -1)"
exec "${INSTALLPATH}/${LATEST}/bin/asdf" exec "asdf" "$@"
